### ISSUE TITLE
500 error with wordpress 5.6

### ISSUE THREAD

**Issue by ahsynv** [pristas-peter/wp-graphql-gutenberg#85]
Hi, we have a 500 error with the last version of WP Graphql Gutenberg plugin : PHP Fatal error: Uncaught Error: Cannot use object of type GraphQL\Type\SchemaConfig as array in \wp-content\plugins\wp-graphql-gutenberg\plugin.php:1080

And we have not access to graphql endpoint, we have 500 too on the site.com/graphql, but when we deactivate WP GraphQL Gutenberg, all is ok

**Comment by bnbabu55** [comment]
I faced the same problem and opened a ticket. Then a theme author suggested that I click on the Update Block Registry on WP Admin panel GraphQL Gutenberg menu, then this error will disappear. I did that I am good now, no more compilation errors.

**Comment by ahsynv** [comment]
@bnbabu55 thank you for you reply ! but i already test it and its not works, already clicked on "Update" button on this page "mysite.com/wp-admin/admin.php?page=wp-graphql-gutenberg-admin" but i have the same problem 🙁

**Comment by stevepepple** [comment]
My team is seeing the same thing, after updating Wordpress to 5.6.1. 

I see an Update failed error when running the Update block registry command.

**Comment by joellembert** [comment]
@ahsynv Try to downgrade Wordpress to 5.4.4. It's Work for me. Use WP Downgrade Plugin.

**Comment by pristas-peter** [comment]
Fixed in #75
